export const products = [
  {
    id: 1,
    type: "для нормальной кожи",
    title: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    image: "./assets/muss_bottle.png",
    alternative: "Muss",
    makeup: [
      "Активные натуральные комплексы",
      "Витамины С, А, РР, В И Е",
      "Солнцезащитные компоненты",
    ],
    price: "2 750",
  },
  {
    id: 2,
    type: "для нормальной кожи",
    title: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    image: "./assets/mask_bottle.png",
    alternative: "Mask",
    makeup: ["Воски", "Минералы", "Масла"],
    price: "3 500",
  },
  {
    id: 3,
    type: "для нормальной кожи",
    title: "Гель для умывания",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    image: "./assets/gel_bottle.png",
    alternative: "Gel",
    makeup: [
      "Минералы",
      "Витамины С, А, РР, В И Е",
      "Солнцезащитные компоненты",
    ],
    price: "1 650",
  },
  {
    id: 4,
    type: "для нормальной кожи",
    title: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    image: "./assets/gift_set_1.png",
    alternative: "Gift_#1",
    makeup: ["Воски", "Минералы", "Масла"],
    price: "4 750",
  },
  {
    id: 5,
    type: "для нормальной кожи",
    title: "Подарочный набор №5",
    description:
      "Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    image: "./assets/gift_set_5.png",
    alternative: "Gift_#5",
    makeup: ["Воски", "Минералы", "Масла"],
    price: "7 520",
  },
];